### ISSUE TITLE
InvalidCastException on dictionaries with 20+ items

### ISSUE THREAD

**Issue by FodderMK** [jacobdufault/fullinspector#164]
Using _FullInspector 2.6.4 (07-11-2016 at 1757)_ I have started getting the following error when I try to add an item to a dictionary with 21 or more elements:

```
InvalidCastException: Cannot cast from source type to destination type.
FullSerializer.Internal.IDictionaryPropertyEditor`3[System.Collections.Generic.Dictionary`2[System.String,System.String],System.String,System.String].AddItemToCollection (System.String item, IDictionary`2& collection, IReorderableListAdaptor adaptor0) (at Assets/FullInspector2/Modules/Collections/Editor/IDictionaryPropertyEditor.cs:24)
UnityEditor.DockArea:OnGUI()
```

FullInspectorExample.cs
```
using System.Collections.Generic;
using FullInspector;

public class FullInspectorExample : BaseScriptableObject
{
	public Dictionary<string, string> TestData;
}
```

FullInspectorExample.asset
```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &11400000
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 9c3c2e22ee7b0a14e8d40361745a14ae, type: 3}
  m_Name: FullInspectorExample
  m_EditorClassIdentifier: 
  _objectReferences: []
  _serializedStateKeys:
  - TestData
  _serializedStateValues:
  - '{"1":null,"2":null,"3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":null,"21":null}'
```
